# This Makefile
# gives instructions to the command
# make
# about how and whether to build programs
#
# The syntax is

# thingtobuld:  what-it-needs-or-depends-on
#    instructions on how to build it
#

# make uses the modification dates to determine
# is the programs need to be re-built

all:  1 clock


#game: project.cpp
	#g++ project.cpp -o project -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio

1: 1.cpp
	g++ 1.cpp -o 1 -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio




